// Generated by tools/make_atlas.py. Do not edit; change the script and rerun it.
#pragma once

#include "gfx/Sprite.h"

namespace atlas {

inline constexpr gfx::AtlasRect kShip{0, 0, 15, 12};
inline constexpr gfx::AtlasRect kFlagship{16, 0, 15, 10};
inline constexpr gfx::AtlasRect kRedAlienA{32, 0, 15, 10};
inline constexpr gfx::AtlasRect kRedAlienB{48, 0, 15, 10};
inline constexpr gfx::AtlasRect kPurpleAlienA{64, 0, 15, 10};
inline constexpr gfx::AtlasRect kPurpleAlienB{80, 0, 15, 10};
inline constexpr gfx::AtlasRect kBlueAlienA{96, 0, 15, 10};
inline constexpr gfx::AtlasRect kBlueAlienB{112, 0, 15, 10};
inline constexpr gfx::AtlasRect kPlayerShot{0, 16, 1, 4};
inline constexpr gfx::AtlasRect kAlienShot{16, 16, 1, 3};
inline constexpr gfx::AtlasRect kPixel{32, 16, 1, 1};
inline constexpr gfx::AtlasRect kFlag{48, 16, 7, 8};
inline constexpr gfx::AtlasRect kExplosion1{64, 16, 15, 11};
inline constexpr gfx::AtlasRect kExplosion2{80, 16, 15, 11};
inline constexpr gfx::AtlasRect kExplosion3{96, 16, 15, 11};
inline constexpr gfx::AtlasRect kExplosion4{112, 16, 15, 11};
inline constexpr gfx::AtlasRect kPlayerExplosion1{0, 32, 15, 11};
inline constexpr gfx::AtlasRect kPlayerExplosion2{16, 32, 15, 11};
inline constexpr gfx::AtlasRect kPlayerExplosion3{32, 32, 15, 11};
inline constexpr gfx::AtlasRect kButton{48, 32, 15, 15};
inline constexpr gfx::AtlasRect kArrow{64, 32, 9, 9};
inline constexpr gfx::AtlasRect kFireIcon{80, 32, 9, 9};

// Font: glyph i of kFontChars is the 8x8 cell at
// (kFontX + (i % kFontColumns) * kGlyphSize, kFontY + (i / kFontColumns) * kGlyphSize).
inline constexpr char kFontChars[] = " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-.!:";
inline constexpr float kFontX = 0;
inline constexpr float kFontY = 64;
inline constexpr int kFontColumns = 16;
inline constexpr float kGlyphSize = 8;

} // namespace atlas
